name: Generar la imagen Docker del servicio y publicarla en Docker Hub
on:
  push:
    branches: [ master ]
jobs:
  push_to_registry:
    name: Publish Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ornelash/temporal
          tag_with_ref: true
